platform:ios, '7.0'
target 'YMStarsProject' do
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'YYKit'
pod 'YTKNetwork'
pod 'MJExtension'
pod 'Masonry'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
end
